name: Node.js CI/CD

on:
    push:
        branches: ["main"]
    pull_request:
        branches: ["main"]

jobs:
    build:
        runs-on: self-hosted

        steps:
            - uses: actions/checkout@v4
            - name: Use Node.js 18.x
              uses: actions/setup-node@v4
              with:
                  node-version: 18.x
                  cache: "npm"
            - name: Create custom .env file
              run: |
                  cat > .env <<EOF
                  RESEND_API_KEY=tu_api_key_de_resend
                  PORT=3000
                  EOF
            - name: instalacion de dependencias
              run: npm install
            - name: Build
              run: npm run build --if-present
            - name: Recargar el servidor
              run: pm2 reload 0
