name: Node.js CI

on:
    push:
        branches: ["main"]
    pull_request:
        branches: ["main"]

jobs:
    build:
        runs-on: self-hosted

        steps:
            - uses: actions/checkout@v4
            - name: Use Node.js 18.x
              uses: actions/setup-node@v4
              with:
                  node-version: 18.x
                  cache: "npm"
            - run: npm install
            - run: npm run build --if-present
